/**
 * Generates the HTML for the Inactivity Warning Email.
 * @param {Object} user - The user document from MongoDB.
 * @param {String} token - The temporary JWT generated by the automation engine.
 */
const getWarningEmailHtml = (user, token) => {
  // FIX: We append the token as a query parameter (?token=...) 
  // This allows the "VerifyAlive.jsx" to read it even if the user is logged out.
  const verifyUrl = `${process.env.FRONTEND_URL}/verify-alive?token=${token}`; 

  return `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 20px auto; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); overflow: hidden; border: 1px solid #e0e0e0;">
      
      <div style="background: linear-gradient(135deg, #1a1a1a 0%, #333333 100%); color: #ffffff; padding: 30px; text-align: center;">
        <h1 style="margin: 0; font-size: 28px; letter-spacing: 1px; text-transform: uppercase;">LegacyChain</h1>
        <p style="margin: 5px 0 0; opacity: 0.8; font-size: 14px;">Secure Digital Asset Handover</p>
      </div>

      <div style="padding: 40px; color: #2c3e50; line-height: 1.8;">
        <h2 style="color: #e74c3c; margin-top: 0; font-size: 22px; border-bottom: 2px solid #f8d7da; padding-bottom: 10px;">⚠️ Security Alert: Inactivity Detected</h2>
        
        <p>Hello,</p>
        <p>Our autonomous engine has detected that your account has been inactive beyond your preset threshold. To prevent the <strong>automatic release</strong> of your encrypted assets to your heirs, we require a manual identity confirmation.</p>
        
        <div style="background-color: #fff5f5; border: 1px solid #feb2b2; border-radius: 8px; padding: 20px; margin: 25px 0; text-align: center;">
          <span style="display: block; font-size: 13px; color: #c53030; text-transform: uppercase; font-weight: bold; margin-bottom: 5px;">Time Remaining in Grace Period</span>
          <span style="font-size: 32px; color: #2d3748; font-weight: 800;">${user.gracePeriod} Minutes</span>
        </div>

        <p style="font-size: 15px;">Clicking the button below will take you to a secure checkpoint where you must enter your password to reset the <strong>Dead Man's Switch</strong>.</p>
        
        <div style="text-align: center; margin: 35px 0;">
          <a href="${verifyUrl}" style="background-color: #2b6cb0; color: #ffffff; padding: 16px 32px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 16px; display: inline-block; box-shadow: 0 4px 6px rgba(43, 108, 176, 0.2);">Confirm Identity & Reset Switch</a>
        </div>

        <p style="font-size: 13px; color: #718096; font-style: italic; text-align: center;">
          Note: This link contains a secure, one-time access token. For your protection, do not forward this email to anyone.
        </p>
      </div>

      <div style="background-color: #f7fafc; color: #a0aec0; padding: 20px; text-align: center; font-size: 12px; border-top: 1px solid #edf2f7;">
        <p style="margin: 0;">This is a system-generated security protocol by <strong>LegacyChain Automation Engine</strong>.</p>
        <p style="margin: 5px 0 0;">&copy; 2026 LegacyChain Labs. All rights reserved.</p>
      </div>
    </div>
  `;
};

module.exports = { getWarningEmailHtml };